version: '3.9'

services:
  core:
    build: 
      context: ./
      dockerfile: './dtcc-model/docker/Dockerfile'
      target: dev
    container_name: dtcccore
    image: dtcc-platform/core
    volumes:
      - ./..:/home/dtcc/core
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  clion:
    build:
      context: ./
      dockerfile: './dtcc-model/docker/Dockerfile'
      target: clion
    container_name: dtccclion
    image: dtcc-platform/clion
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ./..:/home/dtcc/core  
    ports:
      - "7776:22"
      - "7777:7777"

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379
    links:
      - redis-commander

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: dtcc
      HTTP_PASSWORD: dtcc
    ports:
      - 8081:8081

volumes:
  redis_data:
    driver: local
  redis:
  redis-config:



  

