#!/usr/bin/env bash

cd ..; DIR=`pwd`; cd protobuf
CPP_DIR=$DIR/include
PYTHON_DIR=$DIR/src/dtcc

echo "Generating C++ classes into $CPP_DIR..."
protoc --cpp_out=$CPP_DIR dtcc.proto

echo "Generating Python classes into $PYTHON_DIR..."
protoc --python_out=$PYTHON_DIR dtcc.proto
